#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
METAL_DIR = ROOT / "metal"


def c_string_literal(data: str) -> str:
    parts: list[str] = []
    for line in data.splitlines(keepends=True):
        escaped = (
            line.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\t", "\\t")
            .replace("\r", "\\r")
            .replace("\n", "\\n")
        )
        parts.append(f'    "{escaped}"')
    if not parts:
        parts.append('    ""')
    return "\n".join(parts)


def main() -> int:
    files = sorted(METAL_DIR.glob("*.metal"))
    print("/* Auto-generated by tools/embed_metal_sources.py. Do not edit by hand. */")
    print("static NSString *ds4_gpu_embedded_metal_source(NSString *logical_path) {")
    print("    const char *path = logical_path ? [logical_path UTF8String] : NULL;")
    print("    if (!path) return nil;")
    for metal_file in files:
        logical = f"metal/{metal_file.name}"
        source = metal_file.read_text(encoding="utf-8")
        print(f'    if (!strcmp(path, "{logical}") || !strcmp(path, "./{logical}")) {{')
        print("        return [NSString stringWithUTF8String:")
        print(c_string_literal(source))
        print("        ];")
        print("    }")
    print("    return nil;")
    print("}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
